# Generated by Django 5.1.4 on 2024-12-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('name', models.CharField(blank=True, max_length=25, null=True)),
                ('phone', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(db_column='movie_ID', primary_key=True, serialize=False)),
                ('title_ch', models.CharField(blank=True, max_length=50, null=True)),
                ('title_en', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.CharField(blank=True, max_length=255, null=True)),
                ('info', models.CharField(blank=True, max_length=500, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'movie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('show_id', models.IntegerField(primary_key=True, serialize=False)),
                ('row', models.CharField(max_length=5)),
                ('col', models.IntegerField()),
            ],
            options={
                'db_table': 'seat',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('show_id', models.IntegerField(db_column='show_ID', primary_key=True, serialize=False)),
                ('branch', models.CharField(blank=True, max_length=10, null=True)),
                ('room', models.IntegerField(blank=True, null=True)),
                ('show_time', models.DateTimeField(blank=True, null=True)),
                ('remain_seat', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shows',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('branch', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('room_num', models.IntegerField(blank=True, null=True)),
                ('capacity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'theater',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('verify_code', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('seat_row', models.CharField(blank=True, max_length=5, null=True)),
                ('seat_col', models.IntegerField(blank=True, null=True)),
                ('booking_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ticket',
                'managed': False,
            },
        ),
    ]
